### ISSUE TITLE
Getting incorrect results from FastDivide with larger numbers

### ISSUE THREAD

**Issue by snail23** [komrad36/FastDivide#1]
For example, 90 / 10 is giving me 2, 127 / 10 is giving me 2 as well.

Edit:
Also seeing the same thing with the modulo function.

**Comment by komrad36** [comment]
Unable to reproduce. What platform, compiler, and processor, please?

**Comment by snail23** [comment]
Windows 10 x64
Clang 12
i7-9700K

**Comment by komrad36** [comment]
Thank you. And is this using Clang-CL in Visual Studio, Cygwin, WSL, etc...?

**Comment by snail23** [comment]
Just the standalone version directly from the LLVM website:

```
clang --version
clang version 12.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**Comment by komrad36** [comment]
Thank you. I've matched your config, but so far unable to reproduce:

```
C:\Users\Komrad36\Desktop>ver

Microsoft Windows [Version 10.0.19042.804]

C:\Users\Komrad36\Desktop>"C:\Program Files\LLVM\bin\clang.exe" --version
clang version 12.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

C:\Users\Komrad36\Desktop>echo #include "fast-divide.h" > main.cpp

C:\Users\Komrad36\Desktop>echo int main() { return FastDivide(90, 10); } >> main.cpp

C:\Users\Komrad36\Desktop>"C:\Program Files\LLVM\bin\clang.exe" -march=skylake main.cpp -o foo.exe && foo

C:\Users\Komrad36\Desktop>echo %errorlevel%
9
```

Can you please share your test source, or alternatively try the above and let me know what happens?

**Comment by snail23** [comment]
Sure, I'm actually using the C version as I was getting invalid operands with the inline assembly when trying to do that. I also refactored and simplified some parts. I'm also compiling as freestanding. Let me know if you see anything I did wrong, also I just tried copy and pasting your C source and it behaves the same for me.

[https://github.com/snail23/nstdc/blob/main/include/nstdc.h#L1857](https://github.com/snail23/nstdc/blob/main/include/nstdc.h#L1857)

My test benchmark for this function is here: [https://github.com/snail23/nstdc/blob/main/tests/math.c#L205](https://github.com/snail23/nstdc/blob/main/tests/math.c#L205) low numbers work fine and that test passes but if I change it to something higher it fails for some unknown reason, printf'ing the result of higher numbers is returning 2 for the majority that I tested.

CFLAGS:
`CFLAGS=-ffreestanding -flto -fuse-ld=lld -march=native -mno-stack-arg-probe -mtune=native -nostdlib -Ofast -pipe -Weverything`

**Comment by komrad36** [comment]
Ah, there's a bug in your version, line 1867:

`quotient |= 1 << t;`

Should be:

`quotient |= 1ULL << t;`

As the shift might be >= 32. The rest looks good to me.

As substantial changes were made to the source it would have been helpful for me to know that right away! The problem was present in code very different from that in the repo.

I will also note that the C version had to be structured as it is to get MSVC to generate not-terrible code. Clang is much smarter, but I experimented at length and was unable to get optimal codegen from it either. I would _strongly_ recommend the assembly version if possible, and if it's not working we can have a look and see why.

That said, a good C version, like yours, is not TERRIBLE under Clang:

Lang  | Time
------------- | -------------
C  | 0.310
ASM  | 0.283

But it is slower :D

**Comment by snail23** [comment]
That worked, it's always the small things eh? :P
I'll have to try the assembly version again tomorrow as that speedup looks good but thanks for the help!

**Comment by komrad36** [comment]
Cool, glad it's working!! Let me know if you have any issues with the assembly. I tried to get Clang to do the right thing, and it's close, but not quite yet. Maybe someday.

Also as a reminder FastDivide is MIT licensed. Please be sure to include either the full MIT license from FastDivide or just preserve the copyright notice into your own project's license if it's identically licensed (which it appears to be). Thank you!
